# Generated by Django 5.1 on 2024-10-25 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name': 'Type de contrat', 'verbose_name_plural': 'Types de contrat'},
        ),
        migrations.AlterField(
            model_name='job',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobtype', verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employeur'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_filled',
            field=models.BooleanField(default=False, verbose_name='Est pourvu'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='job',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(help_text='Liste des compétences requises', verbose_name='Compétences requises'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(help_text="Conditions d'expérience, formation, etc.", verbose_name='Exigences'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='description',
            field=models.TextField(blank=True, help_text='Description du type de contrat', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
    ]
