# Generated by Django 5.1 on 2024-10-25 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localisation')),
                ('skills', models.TextField(blank=True, help_text='Liste des compétences séparées par des virgules', null=True, verbose_name='Compétences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['-created_at'],
            },
        ),
    ]
